// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXM6wp048_wzYk2srFNh7fviDrBcxCBcs',
    appId: '1:437673069392:web:fb934f271be3d5a728ba55',
    messagingSenderId: '437673069392',
    projectId: 'sindhri-9b9c8',
    authDomain: 'sindhri-9b9c8.firebaseapp.com',
    storageBucket: 'sindhri-9b9c8.firebasestorage.app',
    measurementId: 'G-2J6PSLQ2MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6Z9T8ImP-VDUPndy7Hf8sO4MzKKwab4',
    appId: '1:437673069392:android:1e261b4243a8d05b28ba55',
    messagingSenderId: '437673069392',
    projectId: 'sindhri-9b9c8',
    storageBucket: 'sindhri-9b9c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8P0CjEaWcnb7evyOgAQks9Nxjx-hKsok',
    appId: '1:437673069392:ios:07be8154be5c810628ba55',
    messagingSenderId: '437673069392',
    projectId: 'sindhri-9b9c8',
    storageBucket: 'sindhri-9b9c8.firebasestorage.app',
    iosBundleId: 'com.example.sindhri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8P0CjEaWcnb7evyOgAQks9Nxjx-hKsok',
    appId: '1:437673069392:ios:07be8154be5c810628ba55',
    messagingSenderId: '437673069392',
    projectId: 'sindhri-9b9c8',
    storageBucket: 'sindhri-9b9c8.firebasestorage.app',
    iosBundleId: 'com.example.sindhri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXM6wp048_wzYk2srFNh7fviDrBcxCBcs',
    appId: '1:437673069392:web:d8ce83f3abd35a4f28ba55',
    messagingSenderId: '437673069392',
    projectId: 'sindhri-9b9c8',
    authDomain: 'sindhri-9b9c8.firebaseapp.com',
    storageBucket: 'sindhri-9b9c8.firebasestorage.app',
    measurementId: 'G-DWC3DZHTR6',
  );
}
